const getters = {
  sidebar: state => state.app.sidebar,
  device: state => state.app.device,
  size: state => state.app.size,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  roles: state => state.user.roles,
  permission_routers: state => state.permission.routers,
  addRouters: state => state.permission.addRouters,
  authcode: state => state.user.securityCode,
  usermenu: state => state.user.userMenu,
  rootMenu: state => state.user.rootMenu,
  language: state => state.app.language,
  userInfo: state => state.user.userInfo,
  errorLogs: state => state.errorLog.logs,
  cascadeTableConfig: state => state.components.cascadeTable,
  cascadeTableDefault: state => state.components.cascadeTableDefault,
  appMenu: state => state.user.appMenu,
  systemInfo: state => state.app.systemInfo,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  switchState: state => state.tableSwitch.switchState,
}
export default getters
